image: Visual Studio 2019
environment:
  GH_TOKEN:
      secure: kvUWbn2M0QD68917ZIXoOaIR0fPBkFP/VhABUpEIjs+/AHjQjj9L3+qmVeJYeQ9G

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - choco install msys2 --no-progress -y
  - C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-x86_64-gcc"
  - set PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\mingw64\bin;%PATH%
  - yarn

build_script:
  - yarn prepare-primer3:source
  - yarn deploy-win

test: off
